clc; 
clear; 
close all;

% 文件名
filename = 'file1';

% Step 1: 打开并读取.dpmrpt文件
fid = fopen([filename, '.dpmrpt'], 'r'); % 打开文件
if fid == -1
    error('无法打开文件，请检查文件路径是否正确！');
end

% 读取文件中的数据，跳过前17行
lines = textscan(fid, '%f%f%f%f%f%f%f%f%f%[^\n]', 'HeaderLines', 17);

% 关闭文件
fclose(fid);

% 提取数据，lines是一个1x9的cell数组，每个cell对应一列数据
%data = cell2mat(lines); % 将cell数组转换为矩阵

% Step 2: 数据处理
% data矩阵的列对应：
% 1: ResidenceTime
% 2: X坐标
% 3: Y坐标
% 4: Z坐标
% 5: X速度
% 6: Y速度
% 7: Z速度
% 8: 颗粒直径
% 9: 颗粒ID
pos_x = 2;
pos_y = 3;
pos_z = 4;
vec_x = 5;
vec_y = 6;
vec_z = 7;
p_dia = 8;
p_id = 9;

pv_dim=3;
pos_data=cell2mat(lines(:,[pos_x,pos_y,pos_z]));
vec_data=cell2mat(lines(:,[vec_x,vec_y,vec_z]));
p_total=size(pos_data,1);

dia_data=lines{:,p_dia};
id_data=lines{:,p_id};

clear lines

% Step 3: 将数据写入.vtk文件
vtkFilename = [filename, '_', datestr(datetime('now'), 'yyyy_mm_dd_HH_MM'), '.vtk'];
fid = fopen(vtkFilename, 'w'); % 打开文件用于写入

% 写入VTK文件头
fprintf(fid, '%s\n', '# vtk DataFile Version 4.0');
fprintf(fid, '%s\n', 'Generated by LIGGGHTS');
fprintf(fid, '%s\n', 'ASCII');
fprintf(fid, '%s\n', 'DATASET POLYDATA');

% 写入点数据
fprintf(fid, '%s ', 'POINTS');
fprintf(fid, '%d ', p_total);
fprintf(fid, '%s\n', 'float');
for i = 1:p_total
    for j=1:pv_dim
        if mod(j,pv_dim)==0 && mod(i,pv_dim)==0
            fprintf(fid, '%g\n', pos_data(i,j));
        else
            fprintf(fid, '%g ', pos_data(i,j));
        end
    end
end

% 写入顶点数据
fprintf(fid, '\n');
fprintf(fid, '%s ', 'VERTICES');
fprintf(fid, '%d ', p_total);
fprintf(fid, '%d\n', p_total*2);
for i=1:p_total
    fprintf(fid, '%d ', 1);
    fprintf(fid, '%d\n', i-1);
end

% 下面内容写入颗粒 ID
fprintf(fid, '%s ', 'POINT_DATA');
fprintf(fid, '%d\n', p_total);
fprintf(fid, '%s\n', 'FIELD FieldData 4');
fprintf(fid, '%s ', 'id');
fprintf(fid, '%s ', '1');
fprintf(fid, '%d ', p_total);
fprintf(fid, '%s\n', 'int');
for i=1:p_total
    if mod(i,9)==0
        fprintf(fid, '%g\n' ,id_data(i));
    else
        fprintf(fid, '%g ' ,id_data(i));
    end
end

%下面内容写入颗粒类型
fprintf(fid, '\n');
fprintf(fid, '%s ', 'type');
fprintf(fid, '%s ', '1');
fprintf(fid, '%d ', p_total);
fprintf(fid, '%s\n', 'int');
for i=1:p_total
    if mod(i,9)==0
        fprintf(fid, '%s\n' ,'1');
    else
        fprintf(fid, '%s ' , '1');
    end
end

% 下面内容写入颗粒速度
fprintf(fid, '\n');
fprintf(fid, '%s ' ,'v');
fprintf(fid, '%s ' ,'3');
fprintf(fid, '%d ' ,p_total);
fprintf(fid, '%s\n' ,'double');
for i=1:p_total
    for j=1:pv_dim
        if mod(j,pv_dim)==0 && mod(i,pv_dim)==0
            fprintf(fid, '%g\n', vec_data(i,j));
        else
            fprintf(fid, '%g ', vec_data(i,j));
        end
    end
end

%下面内容写入颗粒半径
fprintf(fid, '\n');
fprintf(fid, '%s ' ,'radius');
fprintf(fid, '%s ' ,'1');
fprintf(fid, '%d ' ,p_total);
fprintf(fid, '%s\n' ,'double');
for i=1:p_total
    if mod(i,9)==0
        fprintf(fid, '%g\n', dia_data(i));
    else
        fprintf(fid, '%g ', dia_data(i));
    end
end
% 关闭文件
fclose(fid);